using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Media;

namespace DinerApplication
{
    public partial class Form2 : Form
    {
        public Form2()
        {
            // Automatically generated by Windows Forms Designer
            InitializeComponent();
        }

        private void Form2_(object sender, EventArgs e)
        {
            // Make the Breakfast, Lunch, and Dinner panels not visible, but the main panel (panel1) is visible by default

            // Original image for panel1 is "Photo by Chris Arthur-Collins on Unsplash" taken from https://unsplash.com/photos/mNu_8f0w-CM?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink
            // Original image for panel2 is "Photo by Olena Sergienko on Unsplash" taken from https://unsplash.com/photos/RUvTvFkEEco?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink
            // Original image for panel3 is "Photo by sk on Unsplash" taken from https://unsplash.com/photos/CK6tjAIMJWM?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink
            // Original image for panel4 is "Photo by Joshua Ryder on Unsplash" taken from https://unsplash.com/photos/I51a7Yy7mQA?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink

            // Inspired by https://www.youtube.com/watch?v=2fLCzLdI978
            panel2.Visible = false;
            panel3.Visible = false;
            panel4.Visible = false;
        }

        private void Form2_FormClosing(object sender, FormClosingEventArgs e)
        {
            // Stop playing the sound
            GlobalVars._soundplayer.Stop();

            Form1 f1 = new Form1();
            // Display Form 1 again
            f1.Show();
        }

        private void breakfastBtn_Click(object sender, EventArgs e)
        {
            // Inspired by https://www.youtube.com/watch?v=2fLCzLdI978

            // Switch to panel2
            panel1.Visible = false;
            panel3.Visible = false;
            panel4.Visible = false;
            // Breakfast panel becomes visible
            panel2.Visible = true;

        }

        private void LunchBtn_Click(object sender, EventArgs e)
        {
            // Inspired by https://www.youtube.com/watch?v=2fLCzLdI978

            // Switch to panel3
            panel1.Visible = false;
            panel2.Visible = false;
            panel4.Visible = false;
            // Lunch panel becomes visible
            panel3.Visible = true;
        }

        private void dinnerBtn_Click(object sender, EventArgs e)
        {
            // Inspired by https://www.youtube.com/watch?v=2fLCzLdI978

            // Switch to panel4
            panel1.Visible = false;
            panel2.Visible = false;
            panel3.Visible = false;
            // Dinner panel becomes visible
            panel4.Visible = true;

            // Start the timer only when the Dinner panel is visible
            timer1.Start();
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panel3_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panel4_Paint(object sender, PaintEventArgs e)
        {

        }

        private void homeBtn3_Click(object sender, EventArgs e)
        {
            returnHome();
        }

        private void homeBtn2_Click(object sender, EventArgs e)
        {
            returnHome();
        }

        private void homeBtn1_Click(object sender, EventArgs e)
        {
            returnHome();
        }

        void returnHome() {
            // Inspired by https://www.youtube.com/watch?v=2fLCzLdI978

            // Make the Breakfast, Lunch, and Dinner panels not visible
            panel2.Visible = false;
            panel3.Visible = false;
            panel4.Visible = false;
            // Switch to main panel (panel1) again
            panel1.Visible = true;
        }

        

        private void timer1_Tick(object sender, EventArgs e)
        {
            // Stop the timer
            timer1.Stop();
            //picBox1.Load(@"C:\Users\Owner\source\repos\HelloWorldWinForms\Images\home_icon.jpg");

        }
    }
}
