using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Drawing.Text;
using System.Media;

namespace DinerApplication
{
    public partial class Form1 : Form
    {
        // Inspired by https://www.youtube.com/watch?v=qOh4ooHg1UU
        public Form1()
        {
            // Automatically generated by Windows Forms Designer
            InitializeComponent();
            // cutlery.wav was downloaded from the URL https://bigsoundbank.com/detail-1193-cutlery-manipulations-on-plate.html
            GlobalVars._soundplayer = new SoundPlayer(@"C:\Users\Owner\source\repos\DinerApplication\Sounds\cutlery.wav");
        }

        private void btnClickThis_Click(object sender, EventArgs e)
        {
            // From https://www.youtube.com/watch?v=ooX_paV5Eoc&list=PL0EE421AE8BCEBA4A&index=88
            
            Form2 f2 = new Form2();
            // Display Form2
            f2.Show();
            // Hide Form 1
            this.Hide();

            GlobalVars._soundplayer.PlayLooping();
        }

        private void backgroundImage1_Click(object sender, EventArgs e)
        {
            // Original image is "Photo by David Garrison from Pexels" taken from www.pexels.com
        }

        private void Form1_Load(object sender, System.EventArgs e)
        {
            // Inspired by https://www.youtube.com/watch?v=cblaNlXDxQQ
            PrivateFontCollection font_col = new PrivateFontCollection();
            // ALBA____.TTF was downloaded from the URL https://www.1001fonts.com/retro-fonts.html?page=2
            font_col.AddFontFile(@"C:\Users\Owner\source\repos\DinerApplication\Fonts\ALBA____.TTF");
            foreach (Control x in this.Controls)
            {
                x.Font = new Font(font_col.Families[0], 20, FontStyle.Bold);
            }
        }

        private void welcome_txt_box_TextChanged(object sender, EventArgs e)
        {
            
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            // Stop the Application completely
            Application.Exit();
        }

    }

    public static class GlobalVars
    {
        // _soundplayer is global so the same soundplayer played in Form1 can be controlled in Form2
        public static SoundPlayer _soundplayer;
    }
}
